name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v4.1.5
    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build da Imagem Docker
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: | 
          cesarags/simple-home-page:v${{ github.run_number }} 
          cesarags/simple-home-page:latest 

  CD-Homolog:
    needs: [CI]
    uses: casoftsolutions/multiplos-ambiente/.github/workflows/deploy.yaml@7f1c015cb61007cfd89a2831657afbbefbbd72d0
    with:
        manifests: k8s/deployment.yaml
        images: cesarags/simple-home-page:v${{ github.run_number }}
        environment: homologacao
    secrets: inherit 

  Teste-Ambinte:
    runs-on: ubuntu-latest
    needs: [CD-Homolog]
    environment: homologacao
    steps:
    - name: Teste de Integração
      run: echo "Teste de Integraçã no ambiente ${{vars.WEB_NAMESPACE}}" }}"

  CD-Producao:
        needs: [CI]
        uses: casoftsolutions/multiplos-ambiente/.github/workflows/deploy.yaml@7f1c015cb61007cfd89a2831657afbbefbbd72d0
        with:
            manifests: k8s/deployment.yaml
            images: cesarags/simple-home-page:v${{ github.run_number }}
            environment: producao
        secrets: inherit 
